// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqYpfUDfuaUqhfWvJUiyyuiJWbkFixlGU',
    appId: '1:911155744021:web:0ebdcda92013d7f58f2d1c',
    messagingSenderId: '911155744021',
    projectId: 'auslan-sign-language',
    authDomain: 'auslan-sign-language.firebaseapp.com',
    storageBucket: 'auslan-sign-language.appspot.com',
    measurementId: 'G-9EPGHZDFMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3b7D3zQymrnSYOA7ylWerSW2dnrw2k0Y',
    appId: '1:911155744021:android:9ab49b743517e7b98f2d1c',
    messagingSenderId: '911155744021',
    projectId: 'auslan-sign-language',
    storageBucket: 'auslan-sign-language.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNTtHvqz9ZfuVocE6zJ2TI61ZwbZHPRwA',
    appId: '1:911155744021:ios:fe720771e8c037128f2d1c',
    messagingSenderId: '911155744021',
    projectId: 'auslan-sign-language',
    storageBucket: 'auslan-sign-language.appspot.com',
    iosBundleId: 'com.example.csit998CapstoneG16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNTtHvqz9ZfuVocE6zJ2TI61ZwbZHPRwA',
    appId: '1:911155744021:ios:fe720771e8c037128f2d1c',
    messagingSenderId: '911155744021',
    projectId: 'auslan-sign-language',
    storageBucket: 'auslan-sign-language.appspot.com',
    iosBundleId: 'com.example.csit998CapstoneG16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqYpfUDfuaUqhfWvJUiyyuiJWbkFixlGU',
    appId: '1:911155744021:web:5b774b53d351f33a8f2d1c',
    messagingSenderId: '911155744021',
    projectId: 'auslan-sign-language',
    authDomain: 'auslan-sign-language.firebaseapp.com',
    storageBucket: 'auslan-sign-language.appspot.com',
    measurementId: 'G-H4L8ZH6P4D',
  );
}